### ISSUE TITLE
Q: Design issue with ApiServlet and expected mapping of /*?

### ISSUE THREAD

**Issue by norrs** [jhannes/action-controller#20]
Is it weird to have this expectation in ApiServlet?

`org.actioncontroller.ActionControllerConfigurationException: class org.actioncontroller.servlet.ApiServlet should have mapping ending with /*, was [/, /configinfo/, *.jsp, *.jspf, *.jspx, *.xsp, *.JSP, *.JSPF, *.JSPX, *.XSP]`

It should be fine to just handle `/` and `/foo` and not having the WebAppContext having to handle `/*` 

Example:

```
internal class AdminWebApp(
    contextPrefix: String, config: ConfigurationBean, dbContext: DbContext,
    dataSourceSupplier: Supplier<DataSource>
) : CommonWebAppContext(contextPrefix) {
    init {
        this.securityHandler =
            basicAuth(
                config.adminUsername,
                config.adminPassword,
                "internal admin"
            )


        val dbContextFilter = addFilter(
            FilterHolder(ApiFilter(dbContext, dataSourceSupplier)),
            "/configinfo",
            EnumSet.of(DispatcherType.REQUEST)
        )
        addServlet(ServletHolder(ApiServlet(ConfigInfoServlet(config))), "/configinfo")

    }
}
``` 

Because then it complains about :

```
javax.servlet.ServletException: org.actioncontroller.servlet.ApiServlet-6cdba6dc==org.actioncontroller.servlet.ApiServlet@9623b286{jsp=null,order=-1,inst=true,async=true,src=EMBEDDED:null}
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:643)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:407)
	at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$2(ServletHandler.java:690)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:714)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:392)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1304)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:879)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:306)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:532)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.server.Server.start(Server.java:469)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89)
	at org.eclipse.jetty.server.Server.doStart(Server.java:414)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at Server.start(Server.kt:93)
	at Server$Companion.main(Server.kt:194)
	at Server.main(Server.kt)
Caused by: org.actioncontroller.ActionControllerConfigurationException: class org.actioncontroller.servlet.ApiServlet should have mapping ending with /*, was [/, /configinfo/, *.jsp, *.jspf, *.jspx, *.xsp, *.JSP, *.JSPF, *.JSPX, *.XSP]
	at org.actioncontroller.servlet.ApiServlet.init(ApiServlet.java:137)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:625)
	... 28 more

```

If app doesn't handle it, is it not the Server's responsibility (in this case jetty) to simply return a 404 from it's error handler?

**Comment by jhannes** [comment]
The problem is that if you map up ApiServlet with `/configinfo`, the servlet container (Jetty) will not forward e.g. "`/configinfo/foo`" to action-controller, defeating the point of route mapping in `@GET`, `@POST` annotations etc.

I made this mistake a few times and spent some time finding out why, so I added this as a sanity check.

If all your routing annotations only contain empty paths, I guess it isn't does make somewhat sense, so I could check the routing map before throwing this exception.

I'll be willing to merge a pull request that checks the routing before throwing this exception. If you want to me add the code to do so, I'd like to understand more about your context first. What are you trying to achieve?
